name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    # to supply options, put them in 'env', like:
    env:
       CIBW_SKIP: pp*
       # CIBW_BUILD: cp39-manylinux_x86_64
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]
        # debug only os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  store_wheels:
    # Commit and push all changed files.
    name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Michele Sardo
    runs-on: ubuntu-20.04
    needs: build_wheels
    steps:
      # Only run on main branch push (e.g. after pull request merge).
      if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "msmttchr@gmail.com"
        git add ./wheelhouse/*.whl
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
