name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    # to supply options, put them in 'env', like:
    env:
      CIBW_SKIP: pp*
      # CIBW_BUILD: cp39-*
      # CIBW_BUILD: cp39-manylinux_x86_64
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Michele Sardo
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        #os: [windows-latest]
    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Copy files for macOS or Linux
        if: runner.os == 'macOS' || runner.os == 'Linux'
        run: |
          echo ${{ runner.os }}
          mkdir -p ./wheeldist
          cp -r ./wheelhouse/*.whl ./wheeldist
      - name: Copy files for Windows
        if: runner.os == 'Windows'
        run: |
          echo ${{ runner.os }}
          mkdir wheeldist -ErrorAction SilentlyContinue
          xcopy /Y .\wheelhouse\*.whl .\wheeldist\
      - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "msmttchr@gmail.com"
          git pull
          git add ./wheeldist/*.whl
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
